UseUnity: false
UseCrownet: true
UseInflux: true
OmnetPort: 12345
UnityAddr: localhost
UnityPort: 54321
InfluxAddr: influxdb
InfluxPort: 8086
# Set a unique Tag to store messages in influxdb.
# default = Messages will be saved in default tag accessible by querying time.
# your-tag = Messages will be saved in your-tag accessible by querying your-tag.
SpecificTag: default
